apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- demo-configmap.yaml

namespace: demo-app-prod

commonLabels:
  env: prod

commonAnnotations:
  note: production deployment of demo-app

# patches using local files

patchesStrategicMerge:
# Resource and Limits
- patch-demo-deployment.yaml
# Replicas count
- patch-demo-hpa.yaml
# Gateway and prefix
- patch-demo-vs.yaml