apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-nginx-01
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: >-
      https://github.com/leoviana00/lab-kustomize-app-demo.git
    path: argocd/apps/squad-a/webserver-nginx-01/overlays/default
    targetRevision: main
    kustomize:
      commonAnnotations:
        app/kustomize: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default