---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: server
        image: nginx:1.17
        volumeMounts:
          - name: demo-app
            mountPath: /usr/share/nginx/html
          - name: nginx-conf
            readOnly: true
            mountPath: /etc/nginx/conf.d
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: "128M"
          limits:
            cpu: 100m
            memory: "256M"
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
      volumes:
      - name: demo-app
        configMap:
          name: demo-app
          items:
          - key: body
            path: index.html
      - name: nginx-conf
        configMap:
          name: demo-app
          items:
          - key: nginx.conf
            path: default.conf
          