apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: webserver-dev

commonLabels:
  env: hom

commonAnnotations:
  note: Development deployment of webserver-go-01

patchesStrategicMerge:
- deployment.yaml
- hpa.yaml
- virtualservice.yaml
- configmap.yaml