apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: hom-

patchesStrategicMerge:
- webserver-nginx-01.application.yaml
- webserver-go-01.application.yaml

# patches:
# - patch: |-
#     - op: replace
#       path: /spec/source/path
#       value: argocd/tenants/demo/demo-app/overlays/development
#   target:
#     group: argoproj.io
#     version: v1alpha1
#     kind: ApplicationSet