apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: webserver-prod

commonLabels:
  env: prod

commonAnnotations:
  note: Production deployment of webserver-go-01

patchesStrategicMerge:
- deployment.yaml
- hpa.yaml
- virtualservice.yaml
- configmap.yaml