---
apiVersion: v1
kind: Service
metadata:
  name: webserver-nginx-01-svc
  namespace: webserver-nginx-01
  labels:
    app: webserver-nginx-01
spec:
  selector:
    app: webserver-nginx-01
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP