apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webserver-go-01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webserver-go-01
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 90
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
        - type: Percent
          value: 20
          periodSeconds: 30
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 20
        - type: Percent
          value: 30
          periodSeconds: 20
      selectPolicy: Max