---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tiny-tools-ds
  labels:
    app: tiny-tools-ds-to-dep
spec:
  selector:
    matchLabels:
      app: tiny-tools-ds-to-dep
  template:
    metadata:
      labels:
        app: tiny-tools-ds-to-dep
    spec:
      containers:
        - name: tiny-tools
          image: giantswarm/tiny-tools:3.11
          resources:
          requests:
            cpu: 200m
            memory: 8Gi
          limits:
            cpu: 400m
            memory: 16Gi