apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- configmap.yaml

namespace: webserver-dev

commonLabels:
  env: dev

commonAnnotations:
  note: Development deployment of webserver-nginx-01

patchesStrategicMerge:
# Resource and Limits
- deployment.yaml
# Replicas count
- hpa.yaml
# Gateway and prefix
- vs.yaml