apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argo-cd
spec:
  generators:
  - git:
      repoURL: https://github.com/leoviana00/lab-kustomize-app-demo.git
      revision: main
      directories:
      - path: argocd/tenants/demo/demo-app/overlays
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: demo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/leoviana00/lab-kustomize-app-demo.git
        targetRevision: main
        path: '{{path}}/staging'
      destination:
        server: https://kubernetes.default.svc