apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  app: demo-app-hom

# patchesStrategicMerge:
# - patch-demo-app.application.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/source/path
      value: argocd/tenants/demo/demo-app/overlays/development
  target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet