apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-go-01
  template:
    metadata:
      labels:
        app: webserver-go-01
    spec:
      containers:
      - name: server
        image: cloudacademydevops/webappecho:latest
        command: ["/go/bin/demo"]
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Default Message"
        - name: BACKGROUND_COLOR
          valueFrom:
            configMapKeyRef:
              name: webserver-go-01-cfg
              key: bgcolor