apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base


namespace: webapp-hom

commonLabels:
  env: hom

commonAnnotations:
  note: staging deployment of webapp

# patches using local files

patchesStrategicMerge:
- deployment.yaml
- hpa.yaml
- virtualservice.yaml
- configmap.yaml